version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY = test
      - DEBUG = True
    depends_on:
      - db
      - redis
      
    
  db:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_USER=benxfoxy@gmail.com
      - POSTGRES_PASSWORD=ben_ya_min
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: